# Generated by Django 5.0.6 on 2024-07-07 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChaiVarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="Firsts/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ML", "MASALA"),
                            ("GR", "GINGER"),
                            ("KI", "KIWI"),
                            ("PL", "PLAIN"),
                            ("EL", "EILAICHI"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
