# Generated by Django 5.0.6 on 2024-06-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=30)),
                ("Subject", models.CharField(max_length=30)),
                ("Message", models.TextField()),
            ],
        ),
    ]
